[package]
name = "treesitter-analyzer"
version = "0.1.0"
authors = ["kiyan42 <yazdani.kiyan@protonmail.com>"]
edition = "2018"

[dependencies]
tree-sitter = "0.17.0"
jsonrpc-tcp-server = "15.0"
xdg = "2.1"

[build-dependencies]
cc="*"
